planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      use_sim_time: false
      allow_unknown: true

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      critics:
        [
          "RotateToGoal",
          "ObstacleFootprint",
          "GoalAlign",
          "PathAlign",
          "PathDist",
          "GoalDist",
        ]
      GoalDist.scale: 1.0
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      ObstacleFootprint.scale: 0.015

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      width: 6
      height: 6
      resolution: 0.03
      rolling_window: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        map_topic: "/projected_map"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: pointcloud
        pointcloud:
          topic: /Laser_map_reliable
          max_obstacle_height: 0.4
          min_obstacle_height: 0.12
          clearing: true
          marking: true
          data_type: "PointCloud2"
          inf_is_valid: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.1

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      width: 3
      height: 3
      resolution: 0.03
      rolling_window: true
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: pointcloud
        pointcloud:
          topic: /Laser_map_reliable
          max_obstacle_height: 0.4
          min_obstacle_height: 0.1
          clearing: true
          marking: true
          data_type: "PointCloud2"
          inf_is_valid: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.08

bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"

amcl:
  ros__parameters:
    use_sim_time: false
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    scan_topic: "/scan"
    map_topic: "/projected_map"
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    laser_min_range: 0.0
    laser_max_range: 8.0
    laser_max_beams: 60
    update_min_d: 0.2
    update_min_a: 0.2

recoveries_server:
  ros__parameters:
    recovery_plugins: ["Spin", "BackUp", "Wait"]
    Spin:
      plugin: "nav2_recoveries/Spin"
    BackUp:
      plugin: "nav2_recoveries/BackUp"
    Wait:
      plugin: "nav2_recoveries/Wait"
